# Generated by Django 5.1.5 on 2025-02-28 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('preco_diaria', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('livre', 'Livre'), ('ocupado', 'Ocupado'), ('manutencao', 'Em manutenção')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField()),
                ('data_saida', models.DateField()),
                ('status', models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pousada.cliente')),
                ('comodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pousada.comodo')),
            ],
        ),
    ]
