# Generated by Django 5.1.6 on 2025-03-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pousada', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comodo',
            name='tipo',
            field=models.CharField(choices=[('quarto_individual', 'Quarto Individual'), ('quarto_casal', 'Quarto Casal'), ('quarto_conjunto', 'Quarto conjunto'), ('quato_familia', 'Quarto Familia')], max_length=50),
        ),
    ]
